Repository appsignal/appsignal-docs, pull requests merged in 2018-11, with the labels that each got.

#192 Mention Ecto 3 setup
  source/elixir/integrations/phoenix.html.md
Labels: writing

#197 update /applicaiton/index.html.md to fix 404
  source/application/index.html.md
Labels: bug

#198 update sequel.html.md to fix 404
  source/ruby/integrations/sequel.html.md
Labels: chore
