Repository appsignal/appsignal-docs, pull requests merged in 2018-05, with the labels that each got.

#166 Add paragraph on skipping session data
  source/elixir/configuration/parameter-filtering.html.md
Labels: chore

#169 Add notes that stress not to send personal data
  source/elixir/configuration/parameter-filtering.html.md
  source/elixir/instrumentation/tagging.html.md
  source/ruby/configuration/parameter-filtering.html.md
  source/ruby/instrumentation/tagging.html.md
Labels: chore

#173 Document request_headers config option
  source/elixir/configuration/options.html.md
  source/ruby/configuration/options.html.md
Labels: writing

#175 Add page about GDPR and fix warnings
  source/_side_nav.html.haml
  source/appsignal/gdpr.html.md
  source/elixir/instrumentation/tagging.html.md
  source/ruby/configuration/parameter-filtering.html.md
  source/ruby/instrumentation/tagging.html.md
Labels: chore, writing

#177 Add section on processor parameter filtering
  source/elixir/configuration/parameter-filtering.html.md.erb
  source/ruby/configuration/parameter-filtering.html.md.erb
  source/shared/_processor_filtering.md
Labels: chore, writing
