Repository appsignal/appsignal-docs, pull requests merged in 2018-04, with the labels that each got.

#158 Warn users to sanitize event bodies
  source/ruby/instrumentation/instrumentation.html.md
Labels: chore

#159 Update Intercom Documentation page, fixes #151
  source/application/integrations/intercom.html.md
  source/images/screenshots/intercom/api_keys.png
  source/images/screenshots/intercom/integration.png
  source/images/screenshots/intercom/oauth.png
Labels: enhancement

#152 ✍️ Add an FAQ page
  source/_side_nav.html.haml
  source/faq.html.md
Labels: chore, growth

#162 Add Heroku Host metrics page
  source/metrics/host-metrics/heroku.html.md
  source/metrics/host.html.haml
Labels: chore
