Repository appsignal/appsignal-docs, pull requests merged in 2019-11, with the labels that each got.

#261 Update Puma docs for new plugin solution
  source/ruby/integrations/puma.html.md
Labels: chore, writing

#268 Ensure we use latest version of design system
  .gitignore
  README.md
  bin/build
  yarn.lock
Labels: bug

#272 Remove old css
  package.json
  postcss.config.js
  source/assets/stylesheets/base/_layout.sass
  source/assets/stylesheets/base/_table.sass
  source/assets/stylesheets/base/_typography.sass
  source/assets/stylesheets/components/_font-awesome.scss
  source/assets/stylesheets/components/_highlight.sass
  source/assets/stylesheets/components/_jump.sass
  source/assets/stylesheets/modules/_article.sass
  source/assets/stylesheets/modules/_docsearch.sass
  source/assets/stylesheets/modules/_footer.sass
  source/assets/stylesheets/modules/_side_nav.sass
  source/assets/stylesheets/utilities/_variables.scss
  source/assets/stylesheets/vendor/_pygments.scss
  webpack.config.js
  yarn.lock
Labels: chore

#273 Fix sidebar opening
  .babelrc
  config.rb
  package.json
  source/_side_nav.html.haml
  source/assets/javascripts/application.js
  source/assets/javascripts/helpers/navigationStore.js
  source/assets/javascripts/navigation.js
  source/layouts/layout.html.haml
  webpack.config.js
  yarn.lock
Labels: chore

#270 Add doc for transaction_debug_mode config option
  data/config_options.yml
Labels: writing

#267 Add page about Ecto/Telemetry configuration
  source/_side_nav.html.haml
  source/elixir/integrations/ecto.html.md
  source/elixir/integrations/phoenix.html.md
Labels: writing

#274 Update plugin-path-decorator.html.md
  source/front-end/plugins/plugin-path-decorator.html.md
Labels: chore
