Repository appsignal/appsignal-docs, pull requests merged in 2019-07, with the labels that each got.

#218 Add search to docs
  source/_docsearch.html.haml
  source/_side_nav.html.haml
  source/layouts/layout.html.haml
  source/stylesheets/application.css.sass
  source/stylesheets/base/_layout.sass
  source/stylesheets/components/_jump.sass
  source/stylesheets/modules/_docsearch.sass
  source/stylesheets/modules/_side_nav.sass
Labels: design, feature

#225 Add new front-end documentation
  source/_side_nav.html.haml
  source/faq.html.md
  source/front-end/configuration/index.html.md
  source/front-end/error-handling.html.md
  source/front-end/index.html.md
  source/front-end/installation.html.md
  source/front-end/integrations/index.html.md
  source/front-end/integrations/react.html.md
  source/front-end/plugins/index.html.md
  source/front-end/plugins/plugin-window-events.html.md
  source/index.html.md
Labels: writing

#228 Add metadata to every page
  config.rb
  lib/appsignal_markdown.rb
  source/images/appsignal-safari-icon.svg
  source/images/logo-color.png
  source/images/logo-color.svg
  source/layouts/layout.html.haml
  source/ruby/index.html.md
Labels: enhancement

#227 Sourcemaps
  source/_side_nav.html.haml
  source/front-end/sourcemaps.html.md.erb
Labels: chore, writing

#229 add example setup for a vue.js application
  source/_side_nav.html.haml
  source/front-end/index.html.md
  source/front-end/integrations/index.html.md
  source/front-end/integrations/vue.html.md
Labels: writing

#230 Add page to explain installing in Elixir umbrella applications
  source/_side_nav.html.haml
  source/elixir/installation.html.md
  source/elixir/installation/umbrella.html.md
Labels: chore, writing
