Repository appsignal/appsignal-docs, pull requests merged in 2019-12, with the labels that each got.

#276 Remove Discord from our docs.
  source/application/integrations/index.html.md
Labels: writing

#275 Add front-end documentation for handling CORS errors:
  source/_side_nav.html.haml
  source/front-end/installation.html.md
  source/front-end/troubleshooting.html.md
Labels: enhancement

#278 Beter namespace filter explanation/example.
  source/ruby/instrumentation/namespaces.html.md
Labels: enhancement

#277 Split the uninstall guide per language
  source/application/index.html.md
  source/elixir/installation.html.md
  source/front-end/installation.html.md
  source/ruby/installation.html.md
Labels: enhancement, writing

#281 Elaborate on Ecto setup in Phoenix apps
  source/elixir/integrations/phoenix.html.md
Labels: writing

#282 Document sleep requirement for Mix and Rake tasks
  source/elixir/instrumentation/mix_tasks.html.md
  source/ruby/integrations/rake.html.md
Labels: chore
