Repository appsignal/appsignal-docs, pull requests merged in 2019-09, with the labels that each got.

#239 Add section about Dokku support
  source/metrics/host.html.md
Labels: chore, support, writing

#241 Add Elixir 1.9 release binary instructions to diagnose page
  source/support/debugging.html.md
Labels: writing

#242 Mention the Phoenix integration dependency on the Absinthe page
  source/elixir/integrations/absinthe.html.md
Labels: writing

#243 Add separate Slack integration page
  source/_side_nav.html.haml
  source/application/integrations/index.html.md
  source/application/integrations/slack.html.md
Labels: chore

#248 Use the right templating example for link templates
  source/application/link-templates.html.md
Labels: bug

#247 Fix misleading wording about front-end beta being limited to some users
  source/front-end/index.html.md
Labels: writing

#250 Remove JS errors beta mentions
  source/_side_nav.html.haml
  source/front-end/error-handling.html.md
  source/front-end/index.html.md
  source/front-end/sourcemaps.html.md.erb
  source/index.html.md
Labels: chore
