Repository appsignal/appsignal-docs, pull requests merged in 2019-10, with the labels that each got.

#238 Add information about Json dependency
  source/elixir/installation.html.md
Labels: writing

#251 Remove :ok matching from Elixir docs
  source/elixir/instrumentation/instrumentation.html.md
Labels: chore

#252 Add documentation for `display` option of the custom metrics syntax.
  source/images/screenshots/custom_metrics_graph_display.png
  source/metrics/custom-metrics/dashboards.html.md
Labels: enhancement

#256 Breadcrumbs docs
  source/_side_nav.html.haml
  source/front-end/breadcrumbs.html.md
  source/front-end/plugins/plugin-breadcrumbs-console.html.md
  source/front-end/plugins/plugin-breadcrumbs-network.html.md
  source/images/screenshots/frontend/breadcrumbs.svg
Labels: writing

#259 Add "Elixir Mix Tasks"
  source/_side_nav.html.haml
  source/elixir/instrumentation/mix_tasks.html.md
Labels: writing

#240 Add "Debugging Phoenix Releases"
  source/_side_nav.html.haml
  source/elixir/releases.html.md
Labels: writing

#260 Mention setting action names in the Plug integration
  source/elixir/integrations/plug.html.md
Labels: writing
