Repository appsignal/appsignal-docs, pull requests merged in 2019-01, with the labels that each got.

#200 Update middleman
  Gemfile
  Gemfile.lock
  config.rb
  source/stylesheets/components/_highlight.css.sass
  source/stylesheets/vendor/pygments.css.scss
Labels: chore, dev happiness

#202 Note Telemetry 3.0 in Phoenix integration docs
  source/elixir/integrations/phoenix.html.md
Labels: chore

#201 Update to middleman v4
  Gemfile
  Gemfile.lock
  config.rb
  data/config_options.yml
  source/shared/_option.html.erb
  source/shared/_options_list.html.erb
  source/stylesheets/_dl/_font-awesome.scss
  source/stylesheets/application.css.sass
  source/stylesheets/base/_layout.sass
  source/stylesheets/base/_table.sass
  source/stylesheets/base/_typography.sass
  source/stylesheets/components/_highlight.sass
  source/stylesheets/components/_jump.sass
  source/stylesheets/modules/_article.sass
  source/stylesheets/modules/_footer.sass
  source/stylesheets/modules/_side_nav.sass
  source/stylesheets/utilities/_variables.scss
  source/stylesheets/vendor/_pygments.scss
Labels: chore, dev happiness

#203 Update jQuery to 3.3.1
  source/javascripts/jquery.js
Labels: chore, dev happiness

#204 Add Change Email Page
  source/_side_nav.html.haml
  source/user-account/email-addresses.html.md
Labels: support, writing

#207 Add Code of Conduct to our docs
  source/appsignal/code-of-conduct.html.md
  source/appsignal/contributing.html.md
Labels: writing

#206 Add Asana integration
  source/_side_nav.html.haml
  source/application/integrations/asana.html.md
  source/application/integrations/index.html.md
  source/images/screenshots/asana/create_task.png
  source/images/screenshots/asana/profile_settings.png
Labels: chore
