Repository appsignal/appsignal-docs, pull requests merged in 2019-03, with the labels that each got.

#213 Remove :extra_applications and umbrella-specific docs
  source/elixir/installation.html.md
Labels: chore

#214 Make it more explicit to use Web Endpoint
  source/elixir/integrations/phoenix.html.md
Labels: writing

#215 Add note to explain that argument needs to be uniq
  source/elixir/integrations/phoenix.html.md
Labels: writing

#216 Update dashboards YAML definition documentation
  source/_side_nav.html.haml
  source/metrics/custom-metrics/dashboards.html.md
  source/metrics/custom.html.md
Labels: writing

#217 Update parameter-filtering.html.md.erb
  source/elixir/configuration/parameter-filtering.html.md.erb
Labels: chore, writing

#212 Document minutely probes
  data/config_options.yml
  source/_side_nav.html.haml
  source/ruby/instrumentation/minutely-probes.html.md
  source/ruby/integrations/mongodb.html.md
  source/ruby/integrations/sidekiq.html.md
Labels: chore, writing

#219 Add docs for Elixir Minutely Probe
  data/config_options.yml
  source/_side_nav.html.haml
  source/elixir/instrumentation/minutely-probes.html.md
  source/ruby/instrumentation/minutely-probes.html.md
Labels: writing
