Repository appsignal/appsignal-docs, pull requests merged in 2019-02, with the labels that each got.

#208 Clarify Ecto instrumentation instructions
  source/elixir/integrations/phoenix.html.md
Labels: writing

#209 Add Google Hangouts to integrations page
  source/_side_nav.html.haml
  source/application/integrations/hangouts.html.md
  source/application/integrations/index.html.md
  source/images/screenshots/hangouts/hangouts_appsignal.png
  source/images/screenshots/hangouts/hangouts_appsignal_form.png
  source/images/screenshots/hangouts/hangouts_webhook.png
  source/images/screenshots/hangouts/hangouts_webhook_configure.png
Labels: enhancement

#210 Add Elixir send_params docs
  data/config_options.yml
  source/elixir/configuration/parameter-filtering.html.md.erb
  source/ruby/configuration/parameter-filtering.html.md.erb
Labels: chore

#211 Add new installation instructions for standalone agent
  source/_side_nav.html.haml
  source/appsignal/standalone-agent.html.md
  source/standalone-agent/installation.html.md
  source/standalone-agent/statsd.html.md
Labels: enhancement
