Repository appsignal/appsignal-docs, pull requests merged in 2020-12, with the labels that each got.

#404 Add slow events guide
  data/navigation.yml
  source/guides/index.html.md
  source/guides/slow-queries.html.md
Labels: writing

#409 Change docs header copy
  source/_header.html.erb
Labels: chore, growth

#410 Fix version
  source/elixir/installation/upgrading-from-1.x-to-2.x.html.md
Labels: writing

#412 Restore the Elixir 1.x documentation
  source/elixir/1.x/command-line/demo.html.md
  source/elixir/1.x/command-line/diagnose.html.md
  source/elixir/1.x/command-line/index.html.md
  source/elixir/1.x/command-line/install.html.md
  source/elixir/1.x/configuration/index.html.md
  source/elixir/1.x/configuration/load-order.html.md
  source/elixir/1.x/configuration/options.html.erb
  source/elixir/1.x/configuration/session-data-filtering.html.md
  source/elixir/1.x/index.html.md
  source/elixir/1.x/installation/index.html.md
  source/elixir/1.x/installation/umbrella.html.md
  source/elixir/1.x/installation/upgrading-from-1.x-to-2.x.html.md
  source/elixir/1.x/instrumentation/exception-handling.html.md
  source/elixir/1.x/instrumentation/index.html.md
  source/elixir/1.x/instrumentation/instrumentation.html.md
  source/elixir/1.x/instrumentation/integrating-appsignal.html.md
  source/elixir/1.x/instrumentation/minutely-probes.html.md
  source/elixir/1.x/instrumentation/mix_tasks.html.md
  source/elixir/1.x/instrumentation/tagging.html.md
  source/elixir/1.x/integrations/absinthe.html.md
  source/elixir/1.x/integrations/ecto.html.md
  source/elixir/1.x/integrations/erlang.html.md
  source/elixir/1.x/integrations/index.html.md
  source/elixir/1.x/integrations/phoenix.html.md
  source/elixir/1.x/integrations/plug.html.md
  source/elixir/1.x/releases.html.md
  source/elixir/1.x/why-nif.html.md
Labels: enhancement
