Repository appsignal/appsignal-docs, pull requests merged in 2020-01, with the labels that each got.

#289 Update Design System to latest version
  package.json
  yarn.lock
Labels: chore

#286 Update data life cycle page and document time
  netlify.toml
  source/_side_nav.html.haml
  source/application/anomaly-detection/index.html.md
  source/appsignal/data-life-cycle.html.md
  source/appsignal/how-appsignal-operates.html.md
  source/appsignal/request-lifecycle.html.md
  source/appsignal/terminology.html.md
  source/front-end/hooks.html.md
  source/support/about-time.html.md
  source/support/debugging.html.md
Labels: chore, writing

#290 Add nodejs documentation
  source/_side_nav.html.haml
  source/nodejs/index.html.md
Labels: writing

#291 Update syntax for Node.js example
  source/nodejs/index.html.md
Labels: writing

#292 Add documentation page on how to setup webserver headers to track
  source/_side_nav.html.haml
  source/assets/images/screenshots/queue_time_graph.png
  source/ruby/instrumentation/request-queue-time.html.md
Labels: enhancement

#294 Add section on performance impact of debug logging on the options page.
  data/config_options.yml
Labels: enhancement

#295 Add page describing how to setup backtrace links.
  source/_side_nav.html.haml
  source/application/backtrace-links.html.md
  source/application/index.html.md
  source/assets/images/screenshots/backtrace_links.png
  source/assets/images/screenshots/repo_url.png
Labels: enhancement

#296 Add documentation about the Rails backtrace cleaner
  source/ruby/integrations/rails.html.md
Labels: enhancement

#297 Add documentation page for incident notification settings.
  source/_side_nav.html.haml
  source/application/index.html.md
  source/application/notification-settings.html.md
  source/assets/images/screenshots/error_incident_notification_defaults.png
  source/assets/images/screenshots/error_incident_notification_options.png
  source/assets/images/screenshots/performance_incident_notification_defaults.png
  source/assets/images/screenshots/performance_incident_notification_options.png
Labels: enhancement

#299 Add page about scrubbing data
  source/application/data-collection.html.md
  source/appsignal/security.html.md
Labels: enhancement

#298 Add page on how to limit requests
  source/_side_nav.html.haml
  source/support/limiting-requests.html.md
Labels: enhancement
