Repository appsignal/appsignal-docs, pull requests merged in 2020-09, with the labels that each got.

#350 Add Security Content Policy docs
  source/assets/stylesheets/modules/_article.sass
  source/front-end/installation.html.md
  source/front-end/troubleshooting.html.md
Labels: enhancement

#351 add ignore actions docs for nodejs
  data/navigation.yml
  source/nodejs/configuration/ignore-actions.html.md.erb
  source/ruby/configuration/ignore-actions.html.md.erb
  source/shared/_ignore_actions.md
Labels: enhancement

#353 update the usage with complete example
  source/ruby/command-line/diagnose.html.md
Labels: enhancement

#355 update known issues
  source/support/known-issues.html.md
  source/support/known-issues/gem-instrumentation-compatibility.html.md
  source/support/known-issues/puma-phased-restart.html.md
Labels: enhancement, writing

#357 Add freddy feedback tool
  source/layouts/layout.html.haml
Labels: feature

#356 App migration FAQ
  source/application/index.html.md
Labels: writing

#359 link GitHub with user profile
  source/user-account/index.html.md
Labels: writing

#361 Rendering metric with and without tags in same graph
  source/metrics/custom.html.md
Labels: writing

#363 Update documentation for v3 of Vue
  source/front-end/integrations/vue.html.md
Labels: writing

#362 Add "Upgrading from AppSignal for Elixir 1.x to 2.x"
  data/navigation.yml
  source/elixir/installation/upgrading-from-1.x-to-2.x.html.md
Labels: writing

#364 add instructions on how to send error to GitHub
  source/application/backtrace-links.html.md
  source/assets/images/screenshots/send_error_to_github.png
Labels: writing
