Repository appsignal/appsignal-docs, pull requests merged in 2020-11, with the labels that each got.

#398 Remove note related to changing of logplex endpoint
  source/metrics/host-metrics/heroku.html.md
Labels: writing

#370 Header refactor
  package.json
  source/_header.html.erb
  yarn.lock
Labels: enhancement

#399 Fix of signup link
  source/_header.html.erb
Labels: bug

#402 Update the link for elixir instrumentation
  source/elixir/instrumentation/integrating-appsignal.html.md
Labels: writing

#401 Add clearer docs about what both JS integrations support
  source/front-end/index.html.md
  source/front-end/installation.html.md
  source/front-end/span.html.md
  source/nodejs/index.html.md
Labels: writing

#329 Update documentation for AppSignal for Elixir 2.0
  data/config_options.yml
  source/elixir/configuration/index.html.md
  source/elixir/configuration/load-order.html.md
  source/elixir/installation/index.html.md
  source/elixir/installation/umbrella.html.md
  source/elixir/instrumentation/exception-handling.html.md
  source/elixir/instrumentation/instrumentation.html.md
  source/elixir/instrumentation/integrating-appsignal.html.md
  source/elixir/instrumentation/mix_tasks.html.md
  source/elixir/instrumentation/tagging.html.md
  source/elixir/integrations/ecto.html.md
  source/elixir/integrations/index.html.md
  source/elixir/integrations/phoenix.html.md
  source/elixir/integrations/plug.html.md
  source/guides/namespaces.html.md
Labels: writing

#400 Remove mention of Elixir 2.0.0-beta.1 from upgrade guide
  source/elixir/installation/upgrading-from-1.x-to-2.x.html.md
Labels: writing

#403 Mention `Appsignal.Plug.put_name/1` in Elixir 3.0 upgrade guide
  source/elixir/installation/upgrading-from-1.x-to-2.x.html.md
Labels: writing

#406 fix header navi links to /ruby and homepage
  source/_header.html.erb
Labels: bug
