Repository appsignal/appsignal-docs, pull requests merged in 2020-05, with the labels that each got.

#315 Fix Elixir tagging documentation.
  source/elixir/instrumentation/tagging.html.md
Labels: enhancement

#316 Update description of warm-up and cooldown
  source/application/anomaly-detection/index.html.md
Labels: writing

#314 Add `set_sample_data` keys and explain how they work
  source/_side_nav.html.haml
  source/assets/images/screenshots/sample_data/custom_data.png
  source/assets/images/screenshots/sample_data/environment.png
  source/assets/images/screenshots/sample_data/params.png
  source/assets/images/screenshots/sample_data/session_data.png
  source/elixir/instrumentation/tagging.html.md
  source/nodejs/instrumentation/span.html.md
  source/ruby/instrumentation/tagging.html.md
Labels: enhancement

#318 Fix Stimulus link on front-end integrations page
  source/front-end/integrations/index.html.md
Labels: chore

#319 Update parameter_filtering.rb initializer
  source/ruby/configuration/parameter-filtering.html.md.erb
Labels: chore

#317 Node.js docs update
  source/_side_nav.html.haml
  source/assets/images/abstract-trace.png
  source/nodejs/index.html.md
  source/nodejs/installation.html.md
  source/nodejs/instrumentation/index.html.md
  source/nodejs/instrumentation/span.html.md
  source/nodejs/instrumentation/tracer.html.md
  source/nodejs/integrations/express.html.md
  source/nodejs/integrations/index.html.md
  source/nodejs/integrations/nextjs.html.md
  source/nodejs/integrations/pg.html.md
  source/nodejs/metrics/index.html.md
  source/nodejs/metrics/meters.html.md
  source/nodejs/metrics/minutely-probes.html.md
  source/nodejs/tracing/index.html.md
  source/nodejs/tracing/scopes.html.md
  source/nodejs/tracing/span-api.html.md
  source/nodejs/tracing/span.html.md
  source/nodejs/tracing/tracer.html.md
Labels: writing

#321 Remove Custom metrics YAML docs.
  source/_side_nav.html.haml
  source/metrics/custom-metrics/dashboards.html.md
  source/metrics/custom.html.md
  source/nodejs/metrics/index.html.md
  source/nodejs/metrics/meters.html.md
Labels: enhancement
