Repository appsignal/appsignal-docs, pull requests merged in 2020-10, with the labels that each got.

#366 Add the right key required for javascript package
  source/front-end/installation.html.md
Labels: writing

#368 add example usage of tracer and span
  source/nodejs/tracing/span.html.md
Labels: writing

#369 Node.js 1.0 docs fixes and tweaks
  data/navigation.yml
  data/tours.yml
  source/_footer.html.erb
  source/application/new-application.html.md
  source/appsignal/terminology.html.md
  source/metrics/custom.html.md
  source/nodejs/command-line/diagnose.html.md
  source/nodejs/command-line/index.html.md
  source/nodejs/command-line/install.html.md
  source/nodejs/configuration/ignore-actions.html.md.erb
  source/nodejs/configuration/ignore-errors.html.md
  source/nodejs/configuration/index.html.md
  source/nodejs/configuration/load-order.html.md
  source/nodejs/index.html.md
  source/nodejs/installation.html.md
  source/nodejs/integrations/apollo.html.md
  source/nodejs/integrations/core.html.md
  source/nodejs/integrations/express.html.md
  source/nodejs/integrations/nextjs.html.md
  source/nodejs/integrations/pg.html.md
  source/nodejs/integrations/redis.html.md
  source/nodejs/metrics/index.html.md
  source/nodejs/metrics/meters.html.md
  source/nodejs/metrics/minutely-probes.html.md
  source/nodejs/tracing/exception-handling.html.md
  source/nodejs/tracing/index.html.md
  source/nodejs/tracing/namespaces.html.md
  source/nodejs/tracing/scopes.html.md
  source/nodejs/tracing/span-api.html.md
  source/nodejs/tracing/span.html.md
  source/nodejs/tracing/tagging.html.md
  source/nodejs/tracing/tracer.html.md
  source/support/operating-systems.html.md
Labels: writing

#377 Update the ignore_actions example to include the app name as well
  source/elixir/configuration/ignore-actions.html.md.erb
Labels: writing

#376 Update the exception handling url for node
  source/nodejs/configuration/ignore-errors.html.md
Labels: writing

#379 Move add new application page to guides
  data/navigation.yml
  netlify.toml
  source/guides/deploy-markers.html.md
  source/guides/index.html.md
  source/guides/new-application.html.md
  source/index.html.md
Labels: enhancement

#375 Add guides section with deploy markers guide
  data/navigation.yml
  netlify.toml
  source/guides/deploy-markers.html.md
  source/guides/index.html.md
  source/guides/new-application.html.md
  source/index.html.md
Labels: enhancement

#380 Move anomaly detection page to features
  data/navigation.yml
  netlify.toml
  source/anomaly-detection/index.html.md
Labels: chore

#381 Add namespace guide
  data/navigation.yml
  source/application/namespaces.html.md
  source/assets/images/screenshots/app_graphs_namespaces.png
  source/guides/index.html.md
  source/guides/namespaces.html.md
Labels: enhancement

#384 Add parameter filtering guide
  data/config_options.yml
  data/navigation.yml
  netlify.toml
  source/application/parameter-filtering.html.md
  source/elixir/configuration/parameter-filtering.html.md.erb
  source/guides/filter-data.html.md
  source/guides/filter-parameters.html.md
  source/guides/namespaces.html.md
  source/ruby/configuration/parameter-filtering.html.md.erb
Labels: enhancement

#386 Add session data filtering guide
  data/navigation.yml
  netlify.toml
  source/application/session-data-filtering.html.md
  source/guides/filter-data/filter-parameters.html.md
  source/guides/filter-data/filter-session-data.html.md
  source/guides/filter-data/index.html.md
  source/ruby/configuration/session-data-filtering.html.md
Labels: enhancement

#387 Nodejs config options
  data/config_options.yml
Labels: enhancement

#388 Add request header collection guide
  data/navigation.yml
  source/application/header-filtering.html.md
  source/guides/filter-data/filter-headers.html.md
  source/guides/filter-data/filter-session-data.html.md
  source/guides/filter-data/index.html.md
Labels: enhancement

#390 Merge ignore actions pages
  data/navigation.yml
  netlify.toml
  source/application/data-collection.html.md
  source/elixir/configuration/ignore-actions.html.md.erb
  source/guides/filter-data/ignore-actions.html.md
  source/nodejs/configuration/ignore-actions.html.md.erb
  source/ruby/configuration/ignore-actions.html.md.erb
  source/shared/_ignore_actions.md
Labels: enhancement

#389 Merge ignore errors pages
  data/navigation.yml
  netlify.toml
  source/application/data-collection.html.md
  source/elixir/configuration/ignore-actions.html.md.erb
  source/elixir/configuration/ignore-errors.html.md
  source/guides/filter-data/filter-headers.html.md
  source/guides/filter-data/ignore-actions.html.md
  source/guides/filter-data/ignore-errors.html.md
  source/guides/filter-data/index.html.md
  source/nodejs/configuration/ignore-actions.html.md.erb
  source/nodejs/configuration/ignore-errors.html.md
  source/ruby/configuration/ignore-actions.html.md.erb
  source/ruby/configuration/ignore-errors.html.md
  source/shared/_ignore_actions.md
Labels: enhancement

#395 Update Node.js default environment value
  data/config_options.yml
Labels: enhancement

#393 Add ignore namespaces guide
  data/navigation.yml
  source/application/namespaces.html.md
  source/guides/filter-data/ignore-actions.html.md
  source/guides/filter-data/ignore-namespaces.html.md
  source/guides/namespaces.html.md
Labels: enhancement

#396 Add configuration guide
  data/navigation.yml
  source/guides/configuration.html.md
  source/guides/deploy-markers.html.md
  source/guides/index.html.md
  source/guides/new-application.html.md
Labels: enhancement

#397 Fix markdown helper error on first build
  bin/build
  config.rb
Labels: chore, dev happiness
