Repository appsignal/appsignal-docs, pull requests merged in 2020-08, with the labels that each got.

#327 Upgrade to latest version of DesignSystem
  .gitignore
  .npmrc
  README.md
  package.json
  source/_footer.html.haml
  source/assets/main.js
  source/assets/stylesheets/components/_font-awesome.scss
  source/assets/stylesheets/design-language-legacy.css.sass
  webpack.config.js
  yarn.lock
Labels: chore

#335 Update design to new layout
  package.json
  source/assets/stylesheets/base/_layout.sass
  source/assets/stylesheets/components/_grid.scss
  source/assets/stylesheets/design-language-legacy.css.sass
  source/assets/stylesheets/modules/_article.sass
  source/assets/stylesheets/modules/_docsearch.sass
  source/assets/stylesheets/modules/_side_nav.sass
  source/layouts/layout.html.haml
  yarn.lock
Labels: design, enhancement

#339 Convert docs footer
  config.rb
  source/_footer.html.erb
  source/_footer.html.haml
  source/assets/stylesheets/design-language-legacy.css.sass
  source/assets/stylesheets/modules/_footer.sass
Labels: enhancement

#340 Update doc search
  source/_docsearch.html.erb
  source/_docsearch.html.haml
  source/assets/stylesheets/modules/_docsearch.sass
Labels: enhancement

#331 Add documentation for our StatsD (HTTP) endpoint on the public-endpoint
  source/_side_nav.html.haml
  source/api/public-endpoint/index.html.md
  source/api/public-endpoint/statsd.html.md
Labels: enhancement

#338 Remove old unused design system
  source/assets/stylesheets/design-system.css
Labels: enhancement

#342 Remove deprecated PUSH API docs, we've deprecated the API since 2018.
  netlify.toml
  source/_side_nav.html.haml
  source/push-api/overview.html.md
Labels: enhancement

#343 Update logplex log drain endpoint to appsignal-endpoint.net
  source/metrics/host-metrics/heroku.html.md
Labels: enhancement

#326 Update docs with Ruby gem 2.11 updates
  data/config_options.yml
  source/_side_nav.html.haml
  source/application/environment-metadata.html.md
  source/metrics/host.html.md
  source/ruby/instrumentation/request-queue-time.html.md
  source/ruby/integrations/active-job.html.md
  source/ruby/integrations/delayed-job.html.md
  source/ruby/integrations/index.html.md
  source/ruby/integrations/que.html.md
  source/ruby/integrations/rails.html.md
  source/ruby/integrations/resque.html.md
  source/ruby/integrations/sidekiq.html.md
Labels: chore, writing

#337 New header
  source/_header.html.erb
  source/_header.html.haml
  source/assets/images/dl_logo/appsignal-logo.svg
  source/assets/javascripts/application.js
  source/layouts/layout.html.haml
Labels: enhancement

#341 Add "on this page" section
  source/assets/javascripts/application.js
  source/assets/javascripts/on_this_page.js
  source/layouts/layout.html.haml
  source/on_this_page.html.erb
Labels: enhancement

#345 Update PagerDuty docs to V2 API
  source/application/integrations/pagerduty.html.md
  source/assets/images/screenshots/pagerduty/service.png
Labels: chore

#344 New sidenav
  config.rb
  data/navigation.yml
  netlify.toml
  source/_side_nav.html.erb
  source/_side_nav.html.haml
  source/appsignal/contributing/code-of-conduct.html.md
  source/appsignal/contributing/index.html.md
  source/assets/javascripts/application.js
  source/assets/stylesheets/design-language-legacy.css.sass
  source/assets/stylesheets/modules/_side_nav.sass
  source/elixir/installation/index.html.md
  source/metrics/dashboards.html.md
  source/metrics/host-metrics/index.html.md
  source/navigation/_page.html.erb
  source/navigation/_section.html.erb
  source/navigation/_sub_page.html.erb
  source/navigation/_sub_section.html.erb
  source/organization/team/index.html.md
  source/support/index.html.md
Labels: enhancement
