Repository appsignal/appsignal-docs, pull requests merged in 2021-02, with the labels that each got.

#425 Update appsignal absinthe plug to 2.x
  source/elixir/integrations/absinthe.html.md
Labels: writing

#429 Namespace in Elixir is added using root_span
  source/guides/namespaces.html.md
Labels: writing

#405 Add documentation for Ruby Breadcrumbs
  data/navigation.yml
  source/ruby/instrumentation/breadcrumbs.html.md
Labels: enhancement

#430 List removed modules and functions in upgrade guide
  source/elixir/installation/upgrading-from-1.x-to-2.x.html.md
Labels: chore

#431 Document JSON metrics public endpoint
  data/navigation.yml
  source/api/public-endpoint/index.html.md
  source/api/public-endpoint/json-metrics.html.md
  source/api/public-endpoint/statsd.html.md
Labels: enhancement

#432 Add public error endpoint
  data/navigation.yml
  source/api/public-endpoint/errors.html.md
  source/api/public-endpoint/index.html.md
Labels: enhancement

#433 Remove mention of AppSignal.Transaction
  source/elixir/integrations/absinthe.html.md
Labels: writing

#434 Improve the overview page of custom integration and tracing
  source/elixir/instrumentation/index.html.md
  source/nodejs/tracing/index.html.md
  source/ruby/instrumentation/index.html.md
Labels: writing
