Repository appsignal/appsignal-docs, pull requests merged in 2021-06, with the labels that each got.

#457 Mention `--send-report` option in Node.js diagnose documentation
  source/nodejs/command-line/diagnose.html.md
Labels: enhancement

#468 Add instructions for KOA.js integration
  data/navigation.yml
  source/nodejs/integrations/index.html.md
  source/nodejs/integrations/koajs.html.md
Labels: writing

#469 Document APPSIGNAL_BUILD_FOR_LINUX_ARM flag
  source/support/operating-systems.html.md
Labels: chore

#470 Update Node.js logPath config default value
  data/config_options.yml
Labels: bug
