Repository appsignal/appsignal-docs, pull requests merged in 2021-05, with the labels that each got.

#453 Add Heroku section under Services & Integrations in the docs.
  data/navigation.yml
  netlify.toml
  source/assets/images/screenshots/heroku-errors-screenshot.png
  source/heroku/dashboards.html.md
  source/heroku/host-metrics.html.md
  source/heroku/logplex-errors.html.md
  source/heroku/setup-logdrain.html.md
  source/heroku/upgrade-logdrain.html.md
Labels: enhancement, writing

#454 Mention the order of Appsignal.Phoenix and Plug.Builder
  source/elixir/installation/umbrella.html.md
Labels: writing

#456 Fix all links pointing to public pages. point them to www.appsignal.com
  README.md
  source/_cookies.html.haml
  source/_footer.html.erb
  source/_header.html.erb
  source/appsignal/contributing/index.html.md
  source/appsignal/gdpr.html.md
  source/appsignal/terminology.html.md
  source/guides/filter-data/ignore-actions.html.md
  source/guides/filter-data/ignore-namespaces.html.md
  source/index.html.md
  source/metrics/host-metrics/index.html.md
Labels: chore

#461 more internal links from http to https
  source/ruby/instrumentation/exception-handling.html.md
Labels: writing

#463 Add uptime monitoring to navigation
  source/_header.html.erb
Labels: chore, design

#464 Edit uptime beta message
  source/uptime-monitoring/index.html.md
Labels: chore

#465 Add MS Teams integration
  data/navigation.yml
  source/application/integrations/index.html.md
  source/application/integrations/teams.html.md
  source/assets/images/screenshots/teams/appsignal_form.png
  source/assets/images/screenshots/teams/deploy.png
  source/assets/images/screenshots/teams/error.png
  source/assets/images/screenshots/teams/test.png
  source/assets/images/screenshots/teams/webhook.png
Labels: enhancement

#462 Add GitHub to integration navigation
  data/navigation.yml
  source/application/integrations/github.html.md
  source/application/integrations/index.html.md
  source/assets/images/screenshots/github/configure.png
  source/assets/images/screenshots/github/github_org.png
  source/assets/images/screenshots/github/github_repo.png
  source/assets/images/screenshots/github/install.png
  source/assets/images/screenshots/github/link_repo.png
  source/assets/images/screenshots/github/linked.png
  source/assets/images/screenshots/github/re_configure.png
  source/assets/images/screenshots/github/select_repositories.png
Labels: writing

#466 We do not store data from cookies
  source/application/tagging.html.md
  source/guides/custom-data/sample-data.html.md
Labels: writing

#467 Update elixir tag example
  source/application/link-templates.html.md
Labels: writing
