Repository appsignal/appsignal-docs, pull requests merged in 2021-01, with the labels that each got.

#413 Add note related to uploading multiple sourcemap files
  source/front-end/sourcemaps.html.md.erb
Labels: writing

#415 Add information related to upload filesize of sourcemap
  source/api/sourcemaps.html.md
  source/front-end/sourcemaps.html.md.erb
Labels: writing

#416 Update Elixir docs for 2.1.0
  source/elixir/instrumentation/exception-handling.html.md
Labels: writing

#417 Add ecto_repos config option
  data/config_options.yml
Labels: writing

#394 Tagging and sample data quide
  data/navigation.yml
  netlify.toml
  source/application/integrations/webhooks.html.md
  source/application/link-templates.html.md
  source/application/tagging.html.md
  source/appsignal/gdpr.html.md
  source/appsignal/terminology.html.md
  source/assets/images/screenshots/sample_data/custom_data.png
  source/assets/images/screenshots/tags/tags.png
  source/elixir/instrumentation/tagging.html.md
  source/elixir/integrations/phoenix.html.md
  source/guides/custom-data/index.html.md
  source/guides/custom-data/sample-data.html.md
  source/guides/custom-data/tagging-request.html.md
  source/guides/filter-data/filter-parameters.html.md
  source/guides/filter-data/index.html.md
  source/guides/index.html.md
  source/guides/namespaces.html.md
  source/nodejs/tracing/span.html.md
  source/nodejs/tracing/tagging.html.md
  source/ruby/instrumentation/tagging.html.md
Labels: enhancement

#420 Remove Ruby's garbage collection config option
  data/config_options.yml
Labels: writing

#422 Make Elixir log_path doc consistent with reality
  data/config_options.yml
Labels: chore
