Repository appsignal/appsignal-docs, pull requests merged in 2021-03, with the labels that each got.

#426 Document Ruby gem 3.0 changes, add upgrade guide
  data/config_options.yml
  data/navigation.yml
  source/ruby/installation/upgrade-from-2-to-3.html.md
  source/ruby/instrumentation/exception-handling.html.md
  source/ruby/integrations/rake.html.md
  source/ruby/integrations/sidekiq.html.md
  source/support/known-issues.html.md
  source/support/known-issues/gem-instrumentation-compatibility.html.md
Labels: chore, writing

#436 Add instructions on how to delete a namespace
  source/application/namespaces.html.md
Labels: feature

#439 Update signup link to be the same as the homepage
  source/_header.html.erb
Labels: chore

#441 Add anomaly detection page to header
  source/_header.html.erb
Labels: bug

#442 Minor improvement on nodejs overview page
  source/nodejs/index.html.md
Labels: writing

#440 Add nodejs links for limiting requests
  source/support/limiting-requests.html.md
Labels: writing

#414 Add the payload related to anomaly detection
  source/application/integrations/webhooks.html.md
Labels: writing
