Repository appsignal/appsignal-docs, pull requests merged in 2021-11, with the labels that each got.

#489 Current node Active LTS is v16
  source/nodejs/index.html.md
Labels: chore

#492 Add missing config options to Node.js
  data/config_options.yml
Labels: chore

#493 Hostname config is now available for standalone agent
  source/standalone-agent/installation.html.md
Labels: writing

#495 Update assets with new navigation
  source/assets/images/screenshots/hangouts/hangouts_appsignal.png
  source/assets/images/screenshots/hangouts/hangouts_appsignal_form.png
  source/assets/images/screenshots/intercom/integration.png
  source/assets/images/screenshots/intercom/oauth.png
  source/assets/images/screenshots/queue_time_graph.png
Labels: chore

#494 Remove unimplemented docs about Node.js features
  data/config_options.yml
  source/guides/filter-data/filter-session-data.html.md
Labels: bug

#496 Update Elixir minutely probes documentation
  source/elixir/instrumentation/minutely-probes.html.md
  source/elixir/integrations/erlang.html.md
Labels: enhancement, writing

#499 Fix broken link and typo in Node.js tracing page
  source/nodejs/tracing/index.html.md
Labels: bug

#498 Update assets to match new design
  source/application/backtrace-links.html.md
  source/assets/images/screenshots/backtrace_links.png
  source/assets/images/screenshots/backtrace_links/backtrace_links.png
  source/assets/images/screenshots/backtrace_links/repo_url.png
  source/assets/images/screenshots/backtrace_links/send_error_to_github.png
  source/assets/images/screenshots/heroku-errors-screenshot.png
  source/assets/images/screenshots/heroku/heroku-errors-screenshot.png
  source/assets/images/screenshots/repo_url.png
  source/assets/images/screenshots/send_error_to_github.png
  source/heroku/logplex-errors.html.md
Labels: chore

#503 Add requestHeaders info for Node.js
  data/config_options.yml
Labels: bug

#504 Rename Node.js apiKey option to pushApiKey
  data/config_options.yml
  source/guides/configuration.html.md
  source/nodejs/configuration/index.html.md
  source/nodejs/configuration/load-order.html.md
  source/nodejs/installation.html.md
  source/nodejs/integrations/apollo.html.md
  source/nodejs/integrations/express.html.md
  source/nodejs/integrations/koajs.html.md
  source/nodejs/integrations/nextjs.html.md
Labels: writing

#507 Update Elixir docs
  source/elixir/1.x/installation/umbrella.html.md
  source/elixir/1.x/installation/upgrading-from-1.x-to-2.x.html.md
  source/elixir/installation/index.html.md
  source/elixir/installation/umbrella.html.md
  source/elixir/installation/upgrading-from-1.x-to-2.x.html.md
  source/elixir/integrations/phoenix.html.md
  source/elixir/integrations/plug.html.md
Labels: writing

#506 Update filtering docs
  data/config_options.yml
  source/guides/filter-data/filter-parameters.html.md
  source/guides/filter-data/filter-session-data.html.md
Labels: writing

#509 Update Elixir docs for instrument with span arg
  source/elixir/instrumentation/instrumentation.html.md
Labels: writing

#508 Update to middleman 4
  .ruby-version
  Gemfile
  Gemfile.lock
Labels: chore
