Repository appsignal/appsignal-docs, pull requests merged in 2022-02, with the labels that each got.

#551 Document trace log_level option
  data/config_options.yml
Labels: writing

#552 Update supported operating systems page
  source/support/operating-systems.html.md
Labels: writing

#553 errorHandler should be assigned before mounting the app
  source/front-end/integrations/vue.html.md
Labels: writing

#556 Update webpack and related build packages
  config.rb
  netlify.toml
  package.json
  source/assets/stylesheets/design-language-legacy.css.sass
  yarn.lock
Labels: chore

#554 Add standalone agent config options
  data/config_options.yml
  data/navigation.yml
  source/shared/_option.html.erb
  source/shared/_options_list.html.erb
  source/standalone-agent/configuration/options.html.erb
  source/standalone-agent/installation.html.md
Labels: writing

#558 Fix file configuration link for each integration
  data/config_options.yml
Labels: writing

#559 Update the shortcut integration documentation
  source/application/integrations/shortcut.html.md
Labels: enhancement

#560 Update enable_host_metrics config option
  data/config_options.yml
Labels: writing

#563 Same site
  source/_header.html.erb
Labels: chore
