Repository appsignal/appsignal-docs, pull requests merged in 2022-01, with the labels that each got.

#522 Add sendParams config option for Node.js
  data/config_options.yml
Labels: bug

#526 Add more details to the log stdout explanation
  data/config_options.yml
Labels: writing

#517 Add warmup notice for people using anomaly detection as cronjob monitor
  source/anomaly-detection/index.html.md
Labels: writing

#527 Rename Clubhouse to Shortcut
  data/navigation.yml
  netlify.toml
  source/application/integrations/clubhouse.html.md
  source/application/integrations/index.html.md
  source/application/integrations/shortcut.html.md
Labels: chore

#528 Add sendSessionData config option docs
  data/config_options.yml
  source/application/session-data-filtering.html.md
  source/appsignal/gdpr.html.md
Labels: chore, enhancement

#529 Add graphql example on fetching the mean
  source/api/graphql-explorer-examples.html.md
Labels: writing

#533 Document send_session_data option for Ruby gem
  data/config_options.yml
Labels: writing

#534 Update Node.js minutely probes documentation
  source/nodejs/integrations/core.html.md
  source/nodejs/metrics/minutely-probes.html.md
Labels: writing

#540 Update minutely probes
  data/config_options.yml
  data/navigation.yml
  netlify.toml
  source/nodejs/instrumentation/minutely-probes.html.md
  source/nodejs/metrics/index.html.md
Labels: writing

#542 Update Node.js installation docs
  source/nodejs/installation.html.md
  source/nodejs/instrumentation/instrumentation.html.md
Labels: writing

#543 Update Node.js custom instrumentation page
  source/nodejs/instrumentation/instrumentation.html.md
Labels: writing

#544 Broken link filter params
  data/config_options.yml
  source/application/parameter-filtering.html.md
Labels: bug

#545 Update notify_of_deploy to mention removal
  source/ruby/command-line/notify_of_deploy.html.md
Labels: writing

#547 Express integration only sends 500 and above exceptions
  source/nodejs/integrations/express.html.md
Labels: writing

#541 Add send_session_data info for Elixir
  data/config_options.yml
Labels: chore

#549 Document the Elixir override config source
  source/elixir/configuration/load-order.html.md
Labels: writing

#548 Document latest config changes
  data/config_options.yml
Labels: writing

#550 Document Ember 4 workaround
  source/front-end/integrations/ember.html.md
Labels: bug, writing
